// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.OperationsCache.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.OperationsCache;
    using Lykke.Service.OperationsCache.Client;
    using Lykke.Service.OperationsCache.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoryEntry
    {
        /// <summary>
        /// Initializes a new instance of the HistoryEntry class.
        /// </summary>
        public HistoryEntry()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoryEntry class.
        /// </summary>
        public HistoryEntry(double feeSize, string id = default(string), System.DateTime? dateTime = default(System.DateTime?), double? amount = default(double?), string currency = default(string), string clientId = default(string), string customData = default(string), string opType = default(string), string feeType = default(string))
        {
            Id = id;
            DateTime = dateTime;
            Amount = amount;
            Currency = currency;
            ClientId = clientId;
            CustomData = customData;
            OpType = opType;
            FeeSize = feeSize;
            FeeType = feeType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime? DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomData")]
        public string CustomData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OpType")]
        public string OpType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeSize")]
        public double FeeSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeType")]
        public string FeeType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
